name: javaomg
version: '1.0-SNAPSHOT'
main: io.github.oceanio.RibbonPlugin
api-version: '1.21.11'

commands:
  villager_fix:
    description: remove enchanted books
  ban_enchant:
    description: Remove banned enchants
    usage: /ban_enchant <chest|inventory> <on|off>
    permission: banenchant.use
permissions:
  banenchant.use:
    description: Allows use of remove enchant command
    default: op